language: node_js
node_js:
- '4'
before_script:
  - npm install -g gulp
script: gulp
before_deploy:
  - cd dist
deploy:
  provider: heroku
  app: gc-pcm
  skip_cleanup: true
  local_dir: dist
  buildpack: php
  api_key:
    secure: eLJvv8neksAFl46k5CcxBKf5IEy0znGb8tPIKpyUOSI9OloEiwwQIYB5i9z+nlKojBGsU1KPEiFZIaTNE/HC1ICFyE35ujm+3lWerauWMXmmLbRXccX4wVMJHsPlt07FPmkFFyF0HlESVJp9nuPU5o7asXddQMx+rKmO7tyZ0JWY9xZuyT9ZUU5Lg/OLbJG0fORoZUNACha4BafXqwsOxbI/757nnC136I6J2eP605Lu1IjrkCgMoNj1unlprCUrBLZZ+N+MSsKtXfF0kr0CISme/4BgvBoOjjSbQAKaRaTGbV4kuBrnL4Kn1a4jppGvzCZOTt22xyEZIeQcy23uqoAicGAMftDP2q5/CSqb3ALYQS5WbIJ5RKD0aiha22b1RQDtbr0v3l8AcWW6j+H4QNrCNhJhjDeMuycDVU+L1ser8ZZUnuDAex8BQ0f88ZM7zfgJbiMNM4jwfQfpAoCcsI0hV0FcHufbeoPE6E0Tj67eWh5DvzAlsOUHU3MbiJEn83lt493PxbFeMlGf6XVJQXF+v0cHHIdhCnq6ZvkqF9aimXQdVKKOU99tjBl1oro00WqvoXuXPUvFNjsPvs82Dzl8JcCQ1qZoKKwO/z7hLRMrLY5WdqwBPLytuEom8fjXZ8KWvF+WLy+/JFSS8PX55RAxMNPM1gSLYRLU5PXzhZk=
